GET https://moises-api.vercel.app/ HTTP/1.1


### REGISTER
POST  https://moises-api.vercel.app/auth/register HTTP/1.1
Content-Type: application/json

{
    "name":"nextTutorial2",
    "username":"nextTutorial2",
    "email":"nextTutorial2@test.com",
    "password":"123123",
    "roles":["admin", "manager"]
}

################################################## LOGIN
POST  https://moises-api.vercel.app/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"nextTutorial2@test.com",
    "password":"123123"
}


############################################################ CONSULTAS DE USUARIOS
GET https://moises-api.vercel.app/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU


################################################################## GET REVENUES
GET https://moises-api.vercel.app/revenues HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU


################################################################ GET INVOICES
GET https://moises-api.vercel.app/invoices HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU
POST   https://moises-api.vercel.app/invoices HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU
    "amount":1400,
    "status":"paid",
    "date":"2025-07-06",
    "customer":"67ae8e89ae9dabe3aa81c4ee"
}


#################################################### GET INVOICES COUNT
GET https://moises-api.vercel.app/invoices/count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU
GET https://moises-api.vercel.app/invoices/status-count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU
GET https://moises-api.vercel.app/invoices/paginate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU



GET https://moises-api.vercel.app/invoices/page-count?q= HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU



######################################################## GET CUSTOMERS
GET https://moises-api.vercel.app/customer HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU

######################################################## GET CUSTOMERS COUNT
GET https://moises-api.vercel.app/customer/count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWU1OTY3YWZmMTY4N2MwMDdjOTk2ZSIsImVtYWlsIjoibmV4dFR1dG9yaWFsMkB0ZXN0LmNvbSIsInVzZXJuYW1lIjoibmV4dFR1dG9yaWFsMiIsImlhdCI6MTczOTkwMjE0MywiZXhwIjoxNzM5OTA1NzQzfQ.pDBhFJ8iRbbL2160gqrfll9KzQGwzBlTJH0Cod3t9CU

